health:
  healthProbeBindAddress: ":8081"
leaderElection:
  leaderElect: false
  resourceName: "github.sanjivmadhavan.io"
  resourceNamespace: "default"
integrations:
  externalDNS:
    targetService:
      name: "kube-dns"
      namespace: "kube-system"
  certManager:
    template:
      spec:
        commonName: "example.com"
        dnsNames:
          - "example.com"
        issuerRef:
          name: "ca-issuer"
          kind: "ClusterIssuer"
